version: "3"

services:
  mongodb:
    restart: always
    container_name: mogodb
    image: mongo:4.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  app:
    restart: always
    container_name: marketapi
    build: .
    depends_on:
      - mongodb
    environment:
      - UDEV= 1
      - ME_CONFIG_MONGODB_ADMINUSERNAME= root
      - ME_CONFIG_MONGODB_ADMINPASSWORD= example
    ports:
      - "7000:7000" # Map 8000 to 8000 of our docker image
    privileged: true
    volumes:
      - ./src:/src # Map ./app directory en docker app folder
    cap_add:
      - SYS_ADMIN
    command: >
      sh -c "python manage.py runserver 0.0.0.0:7000 --settings=api.settings"




